{
 "title": "Solr Dashboard",
 "description": "Solr Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_ping{zk_host=\"$zk_host\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=\"$shard\",replica=\".+\"},replica)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
   },
   {
    "name": "core",
    "query": "label_values(solr_ping{base_url=~\"$base_url\"},core)"
   }
  ]
 },
 "panels": [
  { "title": "Jetty Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{method}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_response_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{status}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "solr_metrics_memory_heap_usage{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_threads{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  }
 ]
}